apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: payment
        image: vmalafeev/web:0.0.2
